### ISSUE TITLE
in `now': stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by mlotfi2005** [jmettraux/rufus-scheduler#269] opened 2018-05-21 19:23 UTC
When I tried to run your example quickstart.rb in windows , I got:

```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:697:in `now': stack level too deep (SystemStackError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:697:in `block in determine_local_tzones'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:697:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:697:in `collect'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:697:in `determine_local_tzones'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:630:in `determine_local_tzone'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:146:in `get_tzone'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:262:in `get_tzone'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:300:in `initialize'
         ... 3398 levels...
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler.rb:542:in `start'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/rufus-scheduler-3.5.0/lib/rufus/scheduler.rb:88:in `initialize'
        from scheduler.rb:4:in `new'
        from scheduler.rb:4:in `<main>'
```

Thanks,

**Comment by jmettraux** [comment] 2018-05-21 22:02
@mlotfi2005 thanks a lot for the issue report. May I know:

* What is your system timezone?
* What version of Windows?
* How did you install Ruby? Via https://rubyinstaller.org/ ?
* What does `bundle exec ruby -r et-orbi -e "EtOrbi._make_info"` (or simply `ruby -r et-orbi -e "EtOrbi._make_info"` yield on your system?

(on my system the above command yields
```
(secs:1526939989.354239,utc~:"0048-05-20 21:59:49.35423898696899414",ltz~:"JCST")
(etz:nil,tnz:"JST",tzid:nil,rv:"2.3.4",rp:"x86_64-darwin14",rorv:nil,astz:nil,eov:"1.1.1",eotnz:#<TZInfo::DataTimezone: Asia/Tokyo>,eotnfz:"+0900",eotlzn:"Asia/Tokyo",debian:nil,centos:nil,osx:"Asia/Tokyo")
``` 
)

Thanks in advance!

**Comment by jmettraux** [comment] 2018-05-22 00:38
Issue reproduced on Appveyor: https://ci.appveyor.com/project/jmettraux/et-orbi/build/job/p80wb2e7flbbd6oo?fullLog=true#L202

**Comment by jmettraux** [comment] 2018-05-22 05:53
@mlotfi2005 another question:

What does `ruby -e "p Time.now.zone"` yield on your system?

Again, thanks in advance.

**Comment by mlotfi2005** [comment] 2018-05-22 12:50
Hi,
- Boston, Suffolk County, Massachusetts, USA, Eastern Time Zone.
- Windows 7.
- ruby was installed  via  https://rubyinstaller.org/

 ruby -r et-orbi -e "EtOrbi._make_info"
(secs:1526993286.908482,utc~:"0048-05-21 12:48:06.9084820747375488",ltz~:nil)
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:697:in `now': stack level too deep (SystemStackError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:697:in `block in determine_local_tzones'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:697:in `each'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:697:in `collect'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:697:in `determine_local_tzones'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:630:in `determine_local_tzone'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:146:in `get_tzone'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:262:in `get_tzone'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:300:in `initialize'
         ... 3402 levels...
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:252:in `now'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:188:in `platform_info'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/et-orbi-1.1.1/lib/et-orbi.rb:203:in `_make_info'
        from -e:1:in `<main>'


ruby -e "p Time.now.zone"
"Eastern Daylight Time"

Thanks,

**Comment by jmettraux** [comment] 2018-05-24 05:45
Hello,

please try with et-orbi 1.1.2, I just released it. It seems to work for me (Windows 7, Ruby 2.2.6p396).

**Comment by jmettraux** [comment] 2018-05-24 23:40
@mlotfi2005 wrote:
> The cursor is still blinking, is the above code supposed to run only one time or every 6s ?

Hello, it's supposed to run only once.

If you want it to run every 6s you'd have to write:
```ruby
scheduler.every '6s' do  # <-- 'every' instead of 'in'
  puts "Hello Rufus at #{Time.now}"
end
```

> if one time why the there is no command prompt yet, cursor still blinking ?

There is a `scheduler.join` call at the end of the quickstart. This tells the current thread to join the scheduler's thread. If you omit this call, the program will cease immediately (before any scheduling happens).

Usually, rufus-scheduler is used in a web app process or in its standalone (daemon) process. The scheduler thread lives in the process and wakes thrice a second (the default) to check if there is any scheduled job to trigger.

Since the scheduler thread gets joined in the quickstart and this scheduler thread is a loop that goes on until interrupted, the Ruby process running the quickstart.rb doesn't exit (and doesn't give back control to the cmd shell, so no command prompt).

I am closing the issue but not the conversation. Feel free to ask any question here, I'll help as best as I can.

Thanks a lot for pointing out at this problem!

**Closed** 2018-05-24 23:40 UTC

**Comment by jmettraux** [comment] 2018-05-29 21:10
> if I understood this scheduler is not meant to be used from the command line, right ?

Well, if you don't mind keeping a command line box open and running the scheduler, nothing prevents you from using it from the command line.

> what did you mean by web app process, any example will be helpful

If you run this command in your cmd box: `ruby -run -ehttpd . -p8000` it starts a Ruby [process](https://en.wikipedia.org/wiki/Process_(computing)) serving the content of the current directory (the dot `.`) on port 8000. This, for example, is a "web app process", serving files over the web. Like the scheduler example above, the process doesn't return immediately, you have to hit `CTRL-C` to force the (web app) process to exit and be given back a command prompt.

Rufus-scheduler is generally used from within a web app process. While the main thread of the process is busy serving http requests, the rufus-scheduler thread manages the scheduled jobs.

Another way to use rufus-scheduler is to give it its own process, usually a [daemon](https://en.wikipedia.org/wiki/Daemon_(computing)) alongside the web app process (if there is one), to schedule at will.

I hope my explanation is not too confusing.

**Comment by mlotfi2005** [comment] 2018-05-30 13:59
Thank you Sir, I appreciate your helps and time.
