### ISSUE TITLE
Need to revive threads phusion passenger

### ISSUE THREAD

**Issue by payoda-suresh** [jmettraux/rufus-scheduler#229] opened 2017-01-05 12:46 UTC
Hi i am using rufus scheduler to send email notifications but due to phusion passenger's smart spawning, the rufus scheduler thread is killed and need to revive threads.can anyone share code to revive threads?

**Comment by jmettraux** [comment] 2017-01-05 21:13
Hello,

unfortunately, I'm the only one to read this issue tracker, it's not really a forum. Second unfortunate thing, I don't use Passenger. I'll try to help anyway.

I guess you are using Ruby on Rails.

If I look the Passenger documentation at https://www.phusionpassenger.com/library/indepth/ruby/spawn_methods/ you probably want something like in your `config.ru`:

```ruby
if defined?(PhusionPassenger)
  PhusionPassenger.on_event(:starting_worker_process) do |forked|
    if forked
      # We're in smart spawning mode.
      $scheduler = Rufus::Scheduler.new
      puts(
        "rufus-scheduler #{$scheduler.class::VERSION} started after fork, " +
        "oid: #{$scheduler.object_id}, pid: #{Process.pid}")
    else
      # We're in direct spawning mode. We don't need to do anything.
    end
  end
else # not Passenger, probably Webrick in dev mode
  $scheduler = Rufus::Scheduler.new
  puts(
    "rufus-scheduler #{$scheduler.class::VERSION} started, " +
    "oid: #{$scheduler.object_id}, pid: #{Process.pid}")
end
```

Then you can skip rufus-scheduler instantiation in the `initializers/` and add some schedules there thanks to `$scheduler`.

Please tell me how it goes.

**Comment by jmettraux** [comment] 2017-01-07 00:47
I will close this non-issue on Monday evening.

**Closed** 2017-01-10 21:54 UTC

**Comment by payoda-suresh** [comment] 2017-01-12 13:56
Thanks for your help.

 I am using Time and expense redmine plugin which uses rufus scheduler for sending email notifications.

 Here is my application details:

  Environment             - production
  centos                       - 6.4
  Apache2
  phusion passenger   - 4.0.41
  ruby                          - 2.1.1
  Rails                         - 3.2.17
  redmine                    - 2.5.1
  Time and expense plugin - 1.7
  rufus-schedular         - 3.0.3

**I have tried your solution:**
  - added the code in RAILS_ROOT/config.ru
  - removed scheduler initialisation in plugin's init.rb file and used $scheduler variable for scheduling jobs.

**Error:**
  while running schedular its gives error as $schedular as nil

**Comment by jmettraux** [comment] 2017-01-12 20:25
Hello,

> while running schedular its gives error as $schedular as nil

`$scheduler` not `$schedular`. Please fix that and try again.

**Comment by payoda-suresh** [comment] 2017-01-13 08:17
Hi,
Sorry schedular is a typo while posting comment.

But used  $scheduler in code and still the error persists.

**Comment by jmettraux** [comment] 2017-01-13 08:18
Please, show me the complete error and its backtrace.

**Comment by payoda-suresh** [comment] 2017-01-13 09:19
Hi,

   I have attached the screenshot of error page.

![rufus_scheduler-1](https://cloud.githubusercontent.com/assets/7310615/21924476/5dbc228a-d99f-11e6-9900-514b53f23cf8.png)
![rufus-scheduler-2](https://cloud.githubusercontent.com/assets/7310615/21924482/64df0640-d99f-11e6-8b5b-9047bfad8a5a.png)

**Comment by jmettraux** [comment] 2017-01-13 09:25
OK, I realize you're using https://github.com/dhanasingh/redmine_wktime

The problem is completely outside of rufus-scheduler. You should discuss the problem with @dhanasingh the redmine_wktime author.

Best regards.

**Comment by dhanasingh** [comment] 2017-01-13 09:37
What is the problem ?
Do you have it configured like the instructions from this page

make sure the following settings are made in your apache settings

PassengerMinInstances 1
RailsAppSpawnerIdleTime 0
PassengerPreStart http://rails-app-url/

**Comment by payoda-suresh** [comment] 2017-01-13 10:39
yes. i have configured as mentioned.but due to this issue http://stackoverflow.com/questions/27980050/rufus-scheduler-not-running-in-production scheduler is not running in production mode.

so i need code to revive threads.

**Comment by dhanasingh** [comment] 2017-01-13 13:42
What version of OS, Apache and Passenger are you using ?

Currently we are using CentOS 6.6, Apache 2.2 and Passenger 5.0.20, it works fine.

**Comment by payoda-suresh** [comment] 2017-01-17 05:39
The following are the details:
           CentOS        - 6.4
           Apache         - 2.2.15
           Passenger    - 4.0.41
           Ruby             - 2.1.1
           Rails             - 3.2.17
           Redmine      - 2.5.1(stable)
           Time and expense plugin - 1.7
           Rufus-scheduler - 3.0.3

          In Development mode it works fine but in production mode the scheduler runs around 10 mins only.
