### ISSUE TITLE
every week scheduler

### ISSUE THREAD

**Issue by federicolucca** [jmettraux/rufus-scheduler#209] opened 2016-06-13 06:37 UTC
Hi everyone,

i'm trying to deploy and exec a job every sunday midnight.
i think the scheduler is resetted every deployment and the new release could be random,when the fixes are ready.

What's the best way to do this scheduler?
`LBSchedulerHelper.scheduler.cron '0 0 * * 0' do  `

this doesn't work for me

thanks
Federico

**Comment by jmettraux** [comment] 2016-06-13 07:18
Hello Federico,

what do you mean by "this doesn't work for me"? Does it mean it "never triggers the schedule"? Does it mean something else?

Is your Sunday job scheduled at each start of the application?
What platform do you deploy to? Heroku? What kind of application did you build? A Rails webapp?

Does it work in your development environment?

... http://www.chiark.greenend.org.uk/~sgtatham/bugs.html ...

Thanks in advance.

**Comment by tangbtqzy** [comment] 2016-06-13 09:28
Hello jmettraux,
After used a long time,I also meet similar problem recently ,when the server'time on sunday, the schedule doesn't trigger
my development environment is:
 ruby 1.9.3
 rails 3.2.15
 ubuntu 14.04

Thinks

**Comment by jmettraux** [comment] 2016-06-13 09:36
Hello @tangbtqzy,

it is considered bad form to "hijack" a conversation thread, referencing an issue from another issue is OK.

Please read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html carefully and then open a new issue report detailing the issue in detail and completely.

Thanks in advance.

**Comment by jmettraux** [comment] 2016-06-13 09:37
@tangbtqzy, @federicolucca and do not forgot to tell me what version of rufus-scheduler you are using.

Remember that I cannot read him. If you want help you have to provide decent information.

**Comment by jmettraux** [comment] 2016-06-13 10:20
I wrote this small "demonstrator": https://github.com/jmettraux/sunfail

It shows that `cron "0 0 * * 0"` is working on my system (details there).

If you can fork this project and modify it so as to show what goes wrong / to prove that it goes wrong with your system please do.

**Comment by tangbtqzy** [comment] 2016-06-13 12:11
@jmettraux 
Thinks for your help , The issue is found what the cron's params  :first => 'xxxx'  wrong just on sunday.

Thinks

**Comment by jmettraux** [comment] 2016-06-13 20:50
@tangbtqzy I don't understand, is your problem solved, yes or no?

If no, could you please fork and modify https://github.com/jmettraux/sunfail so as to show the problem with `:first -> 'xxxx'` in `test.rb` and thus I have a chance to fix it?

**Comment by jmettraux** [comment] 2016-06-14 07:29
I haved added a `first: '3d'` to https://github.com/jmettraux/sunfail and I can see no problems.

**Comment by federicolucca** [comment] 2016-06-15 10:23
Hi everyone,

the mean was "never triggers the schedule".
My application is on Padrino framework,and run on passenger on a Elastic env in Amazon.

i have developed a new module for manage all the schedulers and now each one is working .
i put "scheduler.cron '0 0 * * 0' " for the weekly scheduler and it works last sunday.

i'm waiting the next sunday 


Thanks all
Federico

**Comment by jmettraux** [comment] 2016-06-15 10:26
OK, closing. If something goes wrong, please post a detailed report, I repeat, a detailed report here and I will reopen.

Best regards.

**Closed by jmettraux** 2016-06-15 10:26 UTC
