### ISSUE TITLE
Does one scheduler passes the other defined scheduler ?

### ISSUE THREAD

**Issue by seemalakishore** [jmettraux/rufus-scheduler#306] opened 2020-11-27 11:53 UTC
There are 2 schedulers 
Scheduler that runs every every hour start
```
Scheduler 1
scheduler.cron '0 * * * *' do
//Do some task
end
```
Scheduler that runs every day starting of day and start of hour
```
Scheduler 2
scheduler.cron '0 * * * *' do
//Do another task
end
```
In the scheduler file if scheduler 1 is above scheduler 2 and takes say 3 minutes to complete the task, the scheduler 2 is not executed at all. 
Am I missing something or is there a work around to handle or is this a known issue.

**Comment by seemalakishore** [comment] 2020-11-27 13:54
@jmettraux Can you please let me know about this.

**Comment by jmettraux** [comment] 2020-11-27 14:30
@seemalakishore  wrote:
> @jmettraux Can you please let me know about this.

Hello, it's 23:29 here, I just got back from the gym, I'm going to take a shower now and then I'll look at your issue. Please be patient !

**Comment by jmettraux** [comment] 2020-11-27 15:20
Hello,

I tried to reproduce what you describe.

```ruby

require 'rufus-scheduler'

p `uname -a`
p [ RUBY_VERSION, RUBY_PLATFORM ]
p Rufus::Scheduler::VERSION

tformat = '%F %T.%L'

scheduler = Rufus::Scheduler.new

n = Time.now
m = n.min + 1

puts "now:  #{n.strftime(tformat)}"
puts "m:    #{m}"


# schedule 1 (not scheduler 1)

scheduler.cron "#{m} * * * *" do
  10.times do |i|
    puts "#{Time.now.strftime(tformat)} -> schedule 1 -> #{i}"
    sleep(rand * 3)
  end
  puts "#{Time.now.strftime(tformat)} -> schedule 1 -> over for now."
end


# schedule 2

scheduler.cron "#{m} * * * *" do
  10.times do |i|
    puts "#{Time.now.strftime(tformat)} -> schedule 2 -> #{i}"
    sleep(rand * 3)
  end
  puts "#{Time.now.strftime(tformat)} -> schedule 2 -> over for now."
end


scheduler.join
  #
  # So that the Ruby main threads joins the scheduler thread,
  # so that the Ruby process isn't immediately terminated.
```

Here is a sample output after running that:

```
OpenBSD yawara 6.8 GENERIC.MP#1 amd64
"2.6.6"
"x86_64-openbsd6.7"
"3.6.0"
now:  2020-11-28 00:00:34.508
m:    1
2020-11-28 00:01:00.255 -> schedule 1 -> 0
2020-11-28 00:01:00.255 -> schedule 2 -> 0
2020-11-28 00:01:00.785 -> schedule 2 -> 1
2020-11-28 00:01:02.895 -> schedule 1 -> 1
2020-11-28 00:01:03.535 -> schedule 2 -> 2
2020-11-28 00:01:03.845 -> schedule 1 -> 2
2020-11-28 00:01:05.425 -> schedule 1 -> 3
2020-11-28 00:01:06.345 -> schedule 1 -> 4
2020-11-28 00:01:06.545 -> schedule 2 -> 3
2020-11-28 00:01:07.609 -> schedule 2 -> 4
2020-11-28 00:01:08.105 -> schedule 2 -> 5
2020-11-28 00:01:08.515 -> schedule 1 -> 5
2020-11-28 00:01:09.325 -> schedule 2 -> 6
2020-11-28 00:01:09.815 -> schedule 1 -> 6
2020-11-28 00:01:10.095 -> schedule 1 -> 7
2020-11-28 00:01:11.115 -> schedule 1 -> 8
2020-11-28 00:01:11.205 -> schedule 2 -> 7
2020-11-28 00:01:12.302 -> schedule 1 -> 9
2020-11-28 00:01:13.185 -> schedule 2 -> 8
2020-11-28 00:01:13.575 -> schedule 1 -> over for now.
2020-11-28 00:01:14.185 -> schedule 2 -> 9
2020-11-28 00:01:14.325 -> schedule 2 -> over for now.
```

As you can see, the two schedules (there is a single scheduler, like in your code, although you say "scheduler") are running concurrently. Rufus-scheduler has a pool of working thread and here, each schedule is running in its own thread.

You'll find the whole setup at https://gist.github.com/jmettraux/0056ee7919bf0b7a983d5305a8072877

You wrote:
> Am I missing something or is there a work around to handle or is this a known issue.

If it were a known issue, there would be an open issue for it in the issue tracker. There isn't.

I cannot tell you what you are missing because you don't tell me what your scheduled code does. Maybe schedule 1 and schedule 2 share some resource and a lock is set. Add some logging to your code to see what happens, log the time the schedules wake up, log the time they terminate, etc...

If you cannot come up with a proof that rufus-scheduler is the cause of the issue then I will close this issue. As you can see, rufus-scheduler is, by default, "multi-schedule". You have to find the cause of the problem in your code or provide me with a reproducible proof that rufus-scheduler is wrong.

You haven't told me what version of Ruby you are using, what version of rufus-scheduler you are using, what platform you are using. You haven't told me what your code is supposed to do. Am I supposed to guess all of that? It is very hard to help you in those conditions. The only thing I could do is to prove that my piece of code is behaving as expected, as described in its documentation, as tested in its spec.

It's 00:19 now and I am going to bed.

Best regards.

**Comment by jmettraux** [comment] 2020-11-28 23:06
Closing the issue as there is no further information.

Not closing the conversation though.

**Closed by jmettraux** 2020-11-28 23:06 UTC
