### ISSUE TITLE
PhusionPassenger killing ruby process in idle time.

### ISSUE THREAD

**Issue by mgagan** [jmettraux/rufus-scheduler#189] opened 2015-12-28 10:21 UTC
Hi,
    
Integrating rufus scheduler in Ruby on Rails Application    

rufus-scheduler 3.1.10
ruby 1.9.3
Phusion Passenger 5.0.1
Apache 2.4

scheduler = Rufus::Scheduler.new

scheduler.cron '00 16 * * *' do
  Model.some_method
end

scheduler.cron '00 17 * * *' do
  Model.some_method
end

def self.some_method
end

In development its working fine.

Coming to production its not working

Some of them saying like ruby process killed by PhusionPassenger

I have tried the below configurations like

PassengerSpawnMethod conservative
        (or)
PassengerSpawnMethod smart
        (or)
RailsAppSpawnerIdleTime 0
PassengerMinInstances 1

Can you please help me out of this problem.

**Comment by jmettraux** [comment] 2015-12-28 10:37
Hello,

have you read https://www.phusionpassenger.com/library/indepth/ruby/spawn_methods/ ?

Closing since it's not a rufus-scheduler issue.

**Closed by jmettraux** 2015-12-28 10:37 UTC

**Comment by mgagan** [comment] 2015-12-28 10:42
Hi, 

I already read this https://www.phusionpassenger.com/library/indepth/ruby/spawn_methods/ ?, I know the issue from phusion passenger. still i thought if any one has got same issue. I'm waiting for a solution.

Once i get a solution. lets close it out.

Thanks in advance.

**Comment by jmettraux** [comment] 2015-12-28 10:44
Why don't you ask to the Phusion Passenger mailing list? It's not an issue caused by rufus-scheduler.

**Comment by jmettraux** [comment] 2015-12-28 10:45
https://groups.google.com/forum/#!forum/phusion-passenger

**Comment by jmettraux** [comment] 2015-12-28 11:18
Passenger + Apache configuration reference: https://www.phusionpassenger.com/library/config/apache/reference/

`RailsAppSpawnerIdleTime` is no longer available since Passenger 4.x https://www.phusionpassenger.com/library/config/apache/reference/#railsappspawneridletime

They say you should be using smart spawning, you probably have to use the spawn hooks described in https://www.phusionpassenger.com/library/indepth/ruby/spawn_methods/

Read carefully https://www.phusionpassenger.com/library/config/apache/reference/#passengermininstances and
https://www.phusionpassenger.com/library/config/apache/reference/#passengerprestart .

You probably have to combine `PassengerMinInstances`, `PassengerPreStart` and a spawn hook to get it to work.

Good luck!
